# This notebook is to test trainer.py

## Test to see if get_data works

In [1]:
# Import get_data and preprocess
from splocked.trainer import get_data, preprocess, train_model, save_model

In [ ]:
# Download data from google cloud
df = get_data(nrows=1000)

In [3]:
# Check the shape of the df
df.shape

(1000, 7)

In [4]:
# Check the content of the df
df.head()

review_date   movie_id    user_id  is_spoiler  \
0  10 February 2006  tt0111161  ur1898687        True   
1  6 September 2000  tt0111161  ur0842118        True   
2     3 August 2001  tt0111161  ur1285640        True   
3  1 September 2002  tt0111161  ur1003471        True   
4       20 May 2004  tt0111161  ur0226855        True   

                                         review_text  rating  \
0  In its Oscar year, Shawshank Redemption (writt...      10   
1  The Shawshank Redemption is without a doubt on...      10   
2  I believe that this film is the best story eve...       8   
3  **Yes, there are SPOILERS here**This film has ...      10   
4  At the heart of this extraordinary movie is a ...       8   

                                  review_summary  
0  A classic piece of unforgettable film-making.  
1     Simply amazing. The best film of the 90's.  
2               The best story ever told on film  
3                     Busy dying or busy living?  
4         Great story, wondrously told and acted

## Test to see if preprocess works

In [5]:
X_train, X_test, y_train, y_test, word_to_id = preprocess(df)

/Users/eduardobetancourthernandez/.pyenv/versions/3.7.7/envs/lewagon/lib/python3.7/site-packages/splocked/trainer.py:73: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['is_spoiler'] = boolean_to_binary_array(df['is_spoiler'])


In [6]:
# See the dimensions of embedded arrays
X_train.shape

(700, 997)

In [7]:
# Load the first 30 words of the first review
# They will already be embedded based on X_train vocab
X_train[0][:30]

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.,  2., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24.,  2.,
        3., 25., 26., 27.], dtype=float32)

## Run the model Locally in notebook

In [8]:
# Check the balance of the training set
import numpy as np
np.array(np.unique(y_train, return_counts=True)).T

array([[  0,  34],
       [  1, 666]])

In [9]:
# Check the balance of the testing set
np.array(np.unique(y_test, return_counts=True)).T

array([[  0,  10],
       [  1, 290]])

In [10]:
model = train_model(X_train, y_train, len(word_to_id))

Epoch 1/10
16/16 [==============================] - 12s 744ms/step - loss: 0.5354 - accuracy: 0.9243 - val_loss: 0.3455 - val_accuracy: 0.9526
Epoch 2/10
16/16 [==============================] - 11s 685ms/step - loss: 0.2858 - accuracy: 0.9509 - val_loss: 0.2433 - val_accuracy: 0.9526
Epoch 3/10
16/16 [==============================] - 11s 699ms/step - loss: 0.2222 - accuracy: 0.9509 - val_loss: 0.2067 - val_accuracy: 0.9526
Epoch 4/10
16/16 [==============================] - 11s 690ms/step - loss: 0.1998 - accuracy: 0.9509 - val_loss: 0.1982 - val_accuracy: 0.9526
Epoch 5/10
16/16 [==============================] - 12s 719ms/step - loss: 0.1927 - accuracy: 0.9509 - val_loss: 0.1952 - val_accuracy: 0.9526
Epoch 6/10
16/16 [==============================] - 12s 720ms/step - loss: 0.1868 - accuracy: 0.9509 - val_loss: 0.1931 - val_accuracy: 0.9526
Epoch 7/10
16/16 [==============================] - 12s 719ms/step - loss: 0.1800 - accuracy: 0.9509 - val_loss: 0.1935 - val_accuracy: 0.9526

In [11]:
save_model(model)

TypeError: can't pickle _thread.RLock objects